package orm.mapping;

// Generated 15-ago-2009 12.03.00 by Hibernate Tools 3.2.4.GA

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private String name;

	public Category() {
	}

	public Category(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
