package orm.mapping;

// Generated 15-ago-2009 12.03.00 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

	private String name;
	private Set<File> files = new HashSet<File>(0);
	private Set<Directory> directories = new HashSet<Directory>(0);
	private Set<Group> groups = new HashSet<Group>(0);

	public Type() {
	}

	public Type(String name) {
		this.name = name;
	}

	public Type(String name, Set<File> files, Set<Directory> directories,
			Set<Group> groups) {
		this.name = name;
		this.files = files;
		this.directories = directories;
		this.groups = groups;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	public Set<Directory> getDirectories() {
		return this.directories;
	}

	public void setDirectories(Set<Directory> directories) {
		this.directories = directories;
	}

	public Set<Group> getGroups() {
		return this.groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

}
