package orm.mapping;

// Generated 15-ago-2009 11.19.42 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * File generated by hbm2java
 */
public class File implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Directory directory;
	private Type type;
	private Group group;
	private String name;
	private BigDecimal modified;
	private String location;
	private BigDecimal size;
	private String description;
	private Boolean hidden;
	private Boolean symlink;

	public File() {
	}

	public File(Directory directory, Type type, Group group, String name,
			BigDecimal modified, String location, BigDecimal size,
			String description, Boolean hidden, Boolean symlink) {
		this.directory = directory;
		this.type = type;
		this.group = group;
		this.name = name;
		this.modified = modified;
		this.location = location;
		this.size = size;
		this.description = description;
		this.hidden = hidden;
		this.symlink = symlink;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Directory getDirectory() {
		return this.directory;
	}

	public void setDirectory(Directory directory) {
		this.directory = directory;
	}

	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getModified() {
		return this.modified;
	}

	public void setModified(BigDecimal modified) {
		this.modified = modified;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public BigDecimal getSize() {
		return this.size;
	}

	public void setSize(BigDecimal size) {
		this.size = size;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getHidden() {
		return this.hidden;
	}

	public void setHidden(Boolean hidden) {
		this.hidden = hidden;
	}

	public Boolean getSymlink() {
		return this.symlink;
	}

	public void setSymlink(Boolean symlink) {
		this.symlink = symlink;
	}

}
