package orm.mapping;

// Generated 15-ago-2009 11.19.42 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Type type;
	private Container container;
	private String name;
	private String location;
	private BigDecimal size;
	private BigDecimal freespace;
	private String description;
	private Set<Directory> directories = new HashSet<Directory>(0);
	private Set<File> files = new HashSet<File>(0);

	public Group() {
	}

	public Group(Type type, Container container, String name, String location,
			BigDecimal size, BigDecimal freespace, String description,
			Set<Directory> directories, Set<File> files) {
		this.type = type;
		this.container = container;
		this.name = name;
		this.location = location;
		this.size = size;
		this.freespace = freespace;
		this.description = description;
		this.directories = directories;
		this.files = files;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public Container getContainer() {
		return this.container;
	}

	public void setContainer(Container container) {
		this.container = container;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public BigDecimal getSize() {
		return this.size;
	}

	public void setSize(BigDecimal size) {
		this.size = size;
	}

	public BigDecimal getFreespace() {
		return this.freespace;
	}

	public void setFreespace(BigDecimal freespace) {
		this.freespace = freespace;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Directory> getDirectories() {
		return this.directories;
	}

	public void setDirectories(Set<Directory> directories) {
		this.directories = directories;
	}

	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

}
