package orm.mapping;

// Generated 15-ago-2009 12.03.00 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Directory generated by hbm2java
 */
public class Directory implements java.io.Serializable {

	private Integer id;
	private Type type;
	private Directory directory;
	private Group group;
	private String name;
	private BigDecimal modified;
	private String location;
	private BigDecimal size;
	private String description;
	private Boolean hidden;
	private Boolean symlink;
	private Set<File> files = new HashSet<File>(0);
	private Set<Directory> directories = new HashSet<Directory>(0);

	public Directory() {
	}

	public Directory(Type type, Directory directory, Group group, String name,
			BigDecimal modified, String location, BigDecimal size,
			String description, Boolean hidden, Boolean symlink,
			Set<File> files, Set<Directory> directories) {
		this.type = type;
		this.directory = directory;
		this.group = group;
		this.name = name;
		this.modified = modified;
		this.location = location;
		this.size = size;
		this.description = description;
		this.hidden = hidden;
		this.symlink = symlink;
		this.files = files;
		this.directories = directories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public Directory getDirectory() {
		return this.directory;
	}

	public void setDirectory(Directory directory) {
		this.directory = directory;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getModified() {
		return this.modified;
	}

	public void setModified(BigDecimal modified) {
		this.modified = modified;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public BigDecimal getSize() {
		return this.size;
	}

	public void setSize(BigDecimal size) {
		this.size = size;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getHidden() {
		return this.hidden;
	}

	public void setHidden(Boolean hidden) {
		this.hidden = hidden;
	}

	public Boolean getSymlink() {
		return this.symlink;
	}

	public void setSymlink(Boolean symlink) {
		this.symlink = symlink;
	}

	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	public Set<Directory> getDirectories() {
		return this.directories;
	}

	public void setDirectories(Set<Directory> directories) {
		this.directories = directories;
	}

}
